// <auto-generated />
using System;
using AssetFlow.Auth.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetFlowBackend.Migrations
{
    [DbContext(typeof(UserDbContext))]
    partial class UserDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetFlow.Auth.Models.Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetId"));

                    b.Property<string>("Additional16GbRamStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("additional_16gb_ram_status");

                    b.Property<int?>("AgeingOfAssets")
                        .HasColumnType("int")
                        .HasColumnName("ageing_of_assets");

                    b.Property<string>("AssetsLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assets_location");

                    b.Property<string>("AssetsProcureStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assets_procure_status");

                    b.Property<string>("AssetsStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assets_status");

                    b.Property<DateTime?>("AssignmentDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("assignment_date");

                    b.Property<string>("DasId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("das_id");

                    b.Property<string>("InstallStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("install_status");

                    b.Property<string>("LaptopAssetsTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("laptop_assets_tag");

                    b.Property<string>("LaptopCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("laptop_category");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("make");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("model");

                    b.Property<string>("PowerAdapterDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("power_adapter_details");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.Property<DateTime?>("WarrantyExpiredDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("warranty_expired_date");

                    b.Property<DateTime?>("WarrantyStartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("warranty_start_date");

                    b.HasKey("AssetId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("AssetFlow.Auth.Models.AssetAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("assignment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<string>("CurrentLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("current_location");

                    b.Property<string>("Custodian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("custodian");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("department");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("owner");

                    b.HasKey("AssignmentId");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.ToTable("AssetAssignments");
                });

            modelBuilder.Entity("AssetFlow.Auth.Models.AssetMaintenanceHistory", b =>
                {
                    b.Property<int>("MaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("maintenance_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaintenanceId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("MaintenanceDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("maintenance_date");

                    b.Property<string>("MaintenanceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("maintenance_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("Technician")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("technician");

                    b.HasKey("MaintenanceId");

                    b.HasIndex("AssetId");

                    b.ToTable("AssetMaintenanceHistories");
                });

            modelBuilder.Entity("AssetFlow.Auth.Models.AssetMovementHistory", b =>
                {
                    b.Property<int>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("movement_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovementId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<string>("FromLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("from_location");

                    b.Property<string>("MovedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("moved_by");

                    b.Property<DateTime?>("MovementDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("movement_date");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("movement_type");

                    b.Property<string>("ToLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("to_location");

                    b.HasKey("MovementId");

                    b.HasIndex("AssetId");

                    b.ToTable("AssetMovementHistories");
                });

            modelBuilder.Entity("AssetFlow.Auth.Models.AssetTechnicalSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<string>("Display")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("display");

                    b.Property<string>("Gpu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gpu");

                    b.Property<string>("Processor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("processor");

                    b.Property<string>("Ram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ram");

                    b.Property<string>("Storage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("storage");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.ToTable("AssetTechnicalSpecifications");
                });

            modelBuilder.Entity("AssetFlow.Auth.Models.Fault", b =>
                {
                    b.Property<int>("FaultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FaultId"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReportedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RootCauseNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FaultId");

                    b.HasIndex("AssetId");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("ReportedByUserId");

                    b.ToTable("Faults");
                });

            modelBuilder.Entity("AssetFlow.Auth.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AzureAdId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("azure_ad_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AssetFlow.Auth.Models.AssetAssignment", b =>
                {
                    b.HasOne("AssetFlow.Auth.Models.Asset", "Asset")
                        .WithOne("Assignment")
                        .HasForeignKey("AssetFlow.Auth.Models.AssetAssignment", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssetFlow.Auth.Models.AssetMaintenanceHistory", b =>
                {
                    b.HasOne("AssetFlow.Auth.Models.Asset", "Asset")
                        .WithMany("MaintenanceHistory")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssetFlow.Auth.Models.AssetMovementHistory", b =>
                {
                    b.HasOne("AssetFlow.Auth.Models.Asset", "Asset")
                        .WithMany("Movements")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssetFlow.Auth.Models.AssetTechnicalSpecification", b =>
                {
                    b.HasOne("AssetFlow.Auth.Models.Asset", "Asset")
                        .WithOne("TechnicalSpecification")
                        .HasForeignKey("AssetFlow.Auth.Models.AssetTechnicalSpecification", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("AssetFlow.Auth.Models.Fault", b =>
                {
                    b.HasOne("AssetFlow.Auth.Models.Asset", "Asset")
                        .WithMany("Faults")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetFlow.Auth.Models.User", "Technician")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssetFlow.Auth.Models.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("Reporter");

                    b.Navigation("Technician");
                });

            modelBuilder.Entity("AssetFlow.Auth.Models.Asset", b =>
                {
                    b.Navigation("Assignment")
                        .IsRequired();

                    b.Navigation("Faults");

                    b.Navigation("MaintenanceHistory");

                    b.Navigation("Movements");

                    b.Navigation("TechnicalSpecification")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
